### ISSUE TITLE
seperate the dockin configuration from the kubeconfig file

### ISSUE THREAD

**Issue by walleliu1016** [WeBankFinTech/Dockin-Ops#16]
these content has no business with kubeconfig, It might be clearer to separate them
```
dockin: # Additional custom configuration, the user declares the rules applicable to the cluster and the corresponding cluster id, and declares the default whitelist
  cluster-id: ft01 # cluster id
  rule: test # Rule group, if you need to manage different whitelists for a certificate, you can use rule extension
  whitelist:
    -127.0.0.1 # Permitted ip whitelist, the cluster corresponding to the current certificate, only these ips are allowed to access
```
